name: camera_with_rtmp_example
description: Demonstrates how to use the rtmppublisher plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_with_rtmp:
    path: ../

  path_provider: ^2.0.8
  cupertino_icons: ^1.0.4
  video_player: ^2.2.10
  # e2e: ^0.4.2
  wakelock: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true